In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X,y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42
)

In [3]:
X = torch.tensor(X,dtype=torch.float64)
y = torch.tensor(y,dtype=torch.float64)

In [5]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)

In [6]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
class CustomDataset(Dataset):
    def __init__(self,features,labels): ## Constructor for loading data from memory
        self.features = features
        self.labels = labels
    def __len__(self): ## returns the number of samples in the dataset
        return self.features.shape[0]
    def __getitem__(self, index): ## returns a single sample from the dataset at the given index
        return self.features[index], self.labels[index]

In [11]:
dataset = CustomDataset(X,y)

In [12]:
len(dataset)

10

In [13]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True) ## Create DataLoader with batch size 2 and shuffling enabled

In [16]:
for batch_features,batch_labels in dataloader:
    print("Features:\n",batch_features)
    print("Labels:\n",batch_labels)
    print("--------------------------------------------")


Features:
 tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]], dtype=torch.float64)
Labels:
 tensor([0., 1.], dtype=torch.float64)
--------------------------------------------
Features:
 tensor([[-0.7206, -0.9606],
        [-1.9629, -0.9923]], dtype=torch.float64)
Labels:
 tensor([0., 0.], dtype=torch.float64)
--------------------------------------------
Features:
 tensor([[-1.1402, -0.8388],
        [ 1.0683, -0.9701]], dtype=torch.float64)
Labels:
 tensor([0., 1.], dtype=torch.float64)
--------------------------------------------
Features:
 tensor([[-2.8954,  1.9769],
        [ 1.7774,  1.5116]], dtype=torch.float64)
Labels:
 tensor([0., 1.], dtype=torch.float64)
--------------------------------------------
Features:
 tensor([[ 1.7273, -1.1858],
        [-0.9382, -0.5430]], dtype=torch.float64)
Labels:
 tensor([1., 1.], dtype=torch.float64)
--------------------------------------------


## Implementing Breast Cancer problem with Dataset class and DataLoader 

In [17]:
import torch
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [20]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [21]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [22]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [25]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [26]:
from torch.utils.data import Dataset,DataLoader

In [27]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [28]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [29]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [30]:
import torch.nn as nn 

class SimpleNN(nn.Module):
    def __init__(self,input_features):
        super().__init__()
        self.linear1 = nn.Linear(input_features,3)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(3,3)
        self.relu2 = nn.ReLU()
        self.output = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        x = self.linear1(features)
        x = self.relu1(x)
        x = self.linear2(x)
        x = self.relu2(x)
        x = self.output(x)
        x = self.sigmoid(x)
        return x

In [31]:
learning_rate = 0.001
num_epochs = 100

In [32]:
model = SimpleNN(input_features=X_train_tensor.shape[1])
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)
loss_function = nn.BCELoss()

In [33]:
for epoch in range(num_epochs):
    for batch_features,batch_labels in train_loader:
        y_pred = model(batch_features)
        loss = loss_function(y_pred.squeeze(),batch_labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Epoch : {epoch+1} , Loss : {loss.item()}')


Epoch : 1 , Loss : 0.6775513887405396
Epoch : 2 , Loss : 0.5919510722160339
Epoch : 3 , Loss : 0.5768219232559204
Epoch : 4 , Loss : 0.5855132341384888
Epoch : 5 , Loss : 0.5059501528739929
Epoch : 6 , Loss : 0.46778029203414917
Epoch : 7 , Loss : 0.5260688066482544
Epoch : 8 , Loss : 0.4295276999473572
Epoch : 9 , Loss : 0.5229257941246033
Epoch : 10 , Loss : 0.41428107023239136
Epoch : 11 , Loss : 0.447707861661911
Epoch : 12 , Loss : 0.3917505443096161
Epoch : 13 , Loss : 0.28284651041030884
Epoch : 14 , Loss : 0.29945382475852966
Epoch : 15 , Loss : 0.406044065952301
Epoch : 16 , Loss : 0.23437312245368958
Epoch : 17 , Loss : 0.14671389758586884
Epoch : 18 , Loss : 0.2889351546764374
Epoch : 19 , Loss : 0.16540895402431488
Epoch : 20 , Loss : 0.1505701243877411
Epoch : 21 , Loss : 0.12651264667510986
Epoch : 22 , Loss : 0.1470051109790802
Epoch : 23 , Loss : 0.0668073371052742
Epoch : 24 , Loss : 0.2564634382724762
Epoch : 25 , Loss : 0.03953145071864128
Epoch : 26 , Loss : 0.05800

In [36]:
model.eval()
accuracy_list = []
with torch.no_grad():
    for batch_features,batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred.squeeze() >= 0.5).float()
        accuracy = (y_pred == batch_labels).float().mean()
        accuracy_list.append(accuracy.item())
    print(f'Accuracy : {sum(accuracy_list)/len(accuracy_list) * 100:.2f}%')
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Overall Test Accuracy: {overall_accuracy * 100:.2f}%')

Accuracy : 98.61%
Overall Test Accuracy: 98.61%
