In [1]:
import torch
print(torch.__version__)

2.7.1+cu118


In [2]:
if torch.cuda.is_available():
    print('GPU is available')
    print(f'Using GPU : {torch.cuda.get_device_name(0)}')
else:
    print('GPU not available. Using CPU')

GPU is available
Using GPU : NVIDIA GeForce RTX 4050 Laptop GPU


## Creating a Tensor

#### Using empty 

In [6]:
a=torch.empty(2,3) ## creates an empty tensor of (2,3) dimension

#### Check type

In [7]:
type(a)

torch.Tensor

#### Using ones

In [ ]:
torch.ones(2,3) ## creates tensor of 2X3 dimension with all 1 values

tensor([[1., 1., 1.],
        [1., 1., 1.]])

#### Using zeros 

In [ ]:
torch.zeros(2,3) ## creates tensor of 2X3 dimension with all 0 values

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### Using rand

In [10]:
torch.rand(2,3) ## creates tensor of 2X3 dimension with random values between 0 and 1

tensor([[0.7763, 0.7257, 0.8601],
        [0.5017, 0.2864, 0.0502]])

#### Use of seed 

In [ ]:
torch.manual_seed(100) ## for reproducibility
torch.rand(2,3)

## stores the randomly generated numbers in a tensor

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

#### Using tensor 

In [13]:
torch.tensor([[1,2,3],[4,5,6]]) ## creates a tensor from the given data

tensor([[1, 2, 3],
        [4, 5, 6]])

#### Other ways 

In [18]:
# arange 

print('Using arange : ',torch.arange(0,10,2)) 
 # linspace
print('using linspace : ',torch.linspace(0,10,10))
# eye - create identity tensor of given dimension
print('Using eye : ',torch.eye(5))
# full - create a tensor of given dimension with all values as specified
print('Using full : ',torch.full((3,3),5))

Using arange :  tensor([0, 2, 4, 6, 8])
using linspace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shape

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [20]:
## creating the tensor of the same shape as x 
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [29]:
## to explicitly specify the data type of the tensor
torch.rand_like(x,dtype = torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

## Tensor datatypes

In [24]:
x.dtype

torch.int64

In [25]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
## to change the datatype of previously made tensor of a particular datatype
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

## Mathematical Operations 

### 1. Scalar Operations

In [30]:
# addition 
x + 10 

# substraction
x - 2

# multiplication
x * 2

# divison
x / 3

# int divison
(x*100)/3

# mod
((x * 100)/3) % 2

# power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [33]:
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
print(t1)
print(t2)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])
tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [34]:
# element wise addition 
t1 + t2 

tensor([[1.4812, 0.9536, 0.9538],
        [1.3137, 0.5332, 0.2568]])

In [35]:
# element wise substraction 
t1 - t2

tensor([[-0.4258, -0.4592,  0.6280],
        [-0.4667, -0.4994,  0.1850]])

In [36]:
# element wise mutliplication
t1 * t2

tensor([[0.5032, 0.1746, 0.1288],
        [0.3770, 0.0087, 0.0079]])

In [37]:
# element wise divison
t1/t2

tensor([[0.5534, 0.3499, 4.8557],
        [0.4757, 0.0327, 6.1557]])

In [38]:
# element wise power 
t1 ** t2

tensor([[0.5436, 0.3726, 0.9625],
        [0.4654, 0.1216, 0.9473]])

In [39]:
# element wise mod 
t1 % t2 

tensor([[0.5277, 0.2472, 0.1394],
        [0.4235, 0.0169, 0.0056]])

In [41]:
# absolute value 
t3 = torch.tensor([1,-2,3,-4])
torch.abs(t3)

tensor([1, 2, 3, 4])

In [42]:
# negative value 
torch.neg(t3)

tensor([-1,  2, -3,  4])

In [43]:
# rounding off
t4 = torch.tensor([1.0,2.3,3.7,4.4])
torch.round(t4)

tensor([1., 2., 4., 4.])

In [44]:
# ceil value 
torch.ceil(t4)

tensor([1., 3., 4., 5.])

In [45]:
# floor value 
torch.floor(t4)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp - to keep values of tensor within certain range
torch.clamp(t4,min = 2,max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [7]:
t5 = torch.randint(size=(2,3),low=0,high=10,dtype = torch.float64)
t5

tensor([[6., 8., 7.],
        [0., 3., 5.]], dtype=torch.float64)

In [8]:
# sum - sum of all the values of tensor
torch.sum(t5)

tensor(29., dtype=torch.float64)

In [9]:
# sum of columns 
torch.sum(t5,dim=0)

tensor([ 6., 11., 12.], dtype=torch.float64)

In [10]:
# sum of rows 
torch.sum(t5,dim=1)

tensor([21.,  8.], dtype=torch.float64)

In [13]:
# mean of all the values of tensor
print(torch.mean(t5))

# mean for columns 
print(torch.mean(t5,dim=0))

tensor(4.8333, dtype=torch.float64)
tensor([3.0000, 5.5000, 6.0000], dtype=torch.float64)


In [14]:
# median 
torch.median(t5)

tensor(5., dtype=torch.float64)

In [15]:
# max and min 
print(torch.min(t5))
print(torch.max(t5))

tensor(0., dtype=torch.float64)
tensor(8., dtype=torch.float64)


In [16]:
# product 
torch.prod(t5)

tensor(0., dtype=torch.float64)

In [17]:
# standard deviation 
torch.std(t5)

tensor(2.9269, dtype=torch.float64)

In [18]:
# variance 
torch.var(t5)

tensor(8.5667, dtype=torch.float64)

In [20]:
# argmax - return the position of maximum element of tensor
torch.argmax(t5)

tensor(1)

In [21]:
# argmin - return the position of minimum element of tensor
torch.argmin(t5)

tensor(3)

In [23]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[0, 4, 0],
        [9, 9, 9]])
tensor([[9, 7],
        [0, 2],
        [8, 1]])


In [24]:
# matrix multiplication
torch.matmul(f,g)

tensor([[  0,   8],
        [153,  90]])

In [25]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [26]:
# dot product 
torch.dot(vector1,vector2)

tensor(11)

In [28]:
# transpose 
torch.transpose(f,0,1)

tensor([[0, 9],
        [4, 9],
        [0, 9]])

In [29]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float64)
h

tensor([[3., 3., 2.],
        [3., 5., 8.],
        [2., 3., 4.]], dtype=torch.float64)

In [30]:
# determinant 
torch.det(h)

tensor(-2.0000, dtype=torch.float64)

In [31]:
# inverse 
torch.inverse(h)

tensor([[ 2.0000,  3.0000, -7.0000],
        [-2.0000, -4.0000,  9.0000],
        [ 0.5000,  1.5000, -3.0000]], dtype=torch.float64)

In [37]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[0, 6, 2],
        [8, 4, 1]])
tensor([[6, 1, 2],
        [5, 9, 0]])


In [38]:
# greater than 
i > j

tensor([[False,  True, False],
        [ True, False,  True]])

In [39]:
# less than 
i<j

tensor([[ True, False, False],
        [False,  True, False]])

In [40]:
# equal to 
i == j

tensor([[False, False,  True],
        [False, False, False]])

In [48]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
k

tensor([[3., 5., 7.],
        [0., 4., 4.]], dtype=torch.float64)

In [49]:
# log 
torch.log(k)

tensor([[1.0986, 1.6094, 1.9459],
        [  -inf, 1.3863, 1.3863]], dtype=torch.float64)

In [50]:
# exp
torch.exp(k)

tensor([[2.0086e+01, 1.4841e+02, 1.0966e+03],
        [1.0000e+00, 5.4598e+01, 5.4598e+01]], dtype=torch.float64)

In [51]:
# square root
torch.sqrt(k)

tensor([[1.7321, 2.2361, 2.6458],
        [0.0000, 2.0000, 2.0000]], dtype=torch.float64)

In [52]:
# sigmoid 
torch.sigmoid(k)

tensor([[0.9526, 0.9933, 0.9991],
        [0.5000, 0.9820, 0.9820]], dtype=torch.float64)

In [54]:
# softmax 
torch.softmax(k,dim=0)

tensor([[0.9526, 0.7311, 0.9526],
        [0.0474, 0.2689, 0.0474]], dtype=torch.float64)

In [55]:
# relu 
torch.relu(k)

tensor([[3., 5., 7.],
        [0., 4., 4.]], dtype=torch.float64)

#### Inplace operations - add _ after every functions to make it an inplace function (make changes in the same tensor , not creating the different new tensor after applying operation)

In [ ]:
k.add_(i) ## changes are made to k itself 

tensor([[ 3., 11.,  9.],
        [ 8.,  8.,  5.]], dtype=torch.float64)

In [57]:
k

tensor([[ 3., 11.,  9.],
        [ 8.,  8.,  5.]], dtype=torch.float64)

In [58]:
k.relu_() ## changes are made to k itself

tensor([[ 3., 11.,  9.],
        [ 8.,  8.,  5.]], dtype=torch.float64)

#### this inplace operations are useful for saving memory spaces

## Copying a tensor

In [60]:
k = i 

In [61]:
k 

tensor([[0, 6, 2],
        [8, 4, 1]])

In [62]:
i 

tensor([[0, 6, 2],
        [8, 4, 1]])

In [63]:
k[0][0] = 10

In [64]:
k

tensor([[10,  6,  2],
        [ 8,  4,  1]])

In [65]:
i

tensor([[10,  6,  2],
        [ 8,  4,  1]])

#### so here in both tensors k and i , the changes are made which were applied only to k , so to avoid this clone() is used

In [66]:
k = torch.clone(i)

In [67]:
k

tensor([[10,  6,  2],
        [ 8,  4,  1]])

In [68]:
i

tensor([[10,  6,  2],
        [ 8,  4,  1]])

In [69]:
k[0][0] = 11

In [70]:
k

tensor([[11,  6,  2],
        [ 8,  4,  1]])

In [71]:
i

tensor([[10,  6,  2],
        [ 8,  4,  1]])

#### so as we can see here clearly that i is the cloned version of k , which means the changes made to k will not be reflected to i because both of them are placing at different tensors now not to a same one , which was happening by using assignment operator 

## Tensor operation on GPU

In [72]:
torch.cuda.is_available()

True

In [73]:
device = torch.device('cuda')

In [74]:
# creating a new tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.1030, 0.2843, 0.6594],
        [0.2686, 0.3264, 0.9857]], device='cuda:0')

In [75]:
# moving cpu tensor to gpu

k_gpu = k.to(device)

### comparing computation speed on GPU and CPU

In [78]:
import time 

size = 10000

matrix_cpu1 = torch.rand((size,size))
matrix_cpu2 = torch.rand((size,size))

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2) # on CPU 
cpu_time = time.time() - start_time

print(f'Time on CPU : {cpu_time : .4f} seconds')

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2) # on GPU
torch.cuda.synchronize() # ensure all GPU operations are complete

gpu_time = time.time() - start_time
print(f'Time on GPU : {gpu_time : .4f} seconds')

print('\n Speedup (CPU time / GPU time) : ', cpu_time/gpu_time)

Time on CPU :  3.1348 seconds
Time on GPU :  1.6043 seconds

 Speedup (CPU time / GPU time) :  1.9540546469072189


## Reshaping Tensors

In [ ]:
k.unsqueeze(0).shape ## adding extra dimension at 0th index

torch.Size([1, 2, 3])

In [80]:
k.squeeze().shape ## removing all the dimensions of size 1

torch.Size([2, 3])

In [82]:
k.permute(1,0).shape ## swapping the dimensions

torch.Size([3, 2])

## NumPy and PyTorch

In [83]:
import numpy as np 

In [84]:
t1 = torch.tensor([1,2,3])

In [ ]:
# tensor to numpy array
t1_np_array = t1.numpy()

In [86]:
np_array = np.array([4,5,6])    

In [ ]:
# numpy array to torch tensor
torch.from_numpy(np_array)

tensor([4, 5, 6], dtype=torch.int32)