In [1]:
import torch
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [6]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
565       20.130         28.25          131.20     1261.0          0.09780   
33        19.270         26.47          127.90     1162.0          0.09401   
22        15.340         14.26          102.50      704.4          0.10730   
124       13.370         16.39           86.10      553.5          0.07115   
418       12.700         12.17           80.88      495.0          0.08785   
..           ...           ...             ...        ...              ...   
342       11.060         14.96           71.49      373.9          0.10330   
455       13.380         30.72           86.34      557.2          0.09245   
475       12.830         15.73           82.89      506.9          0.09040   
206        9.876         17.27           62.92      295.4          0.10890   
416        9.405         21.70           59.60      271.2          0.10440   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
565           0.10340         0.14400              0.09791         0.1752   
33            0.17190         0.16570              0.07593         0.1853   
22            0.21350         0.20770              0.09756         0.2521   
124           0.07325         0.08092              0.02800         0.1422   
418           0.05794         0.02360              0.02402         0.1583   
..                ...             ...                  ...            ...   
342           0.09097         0.05397              0.03341         0.1776   
455           0.07426         0.02819              0.03264         0.1375   
475           0.08269         0.05835              0.03078         0.1705   
206           0.07232         0.01756              0.01952         0.1934   
416           0.06159         0.02047              0.01257         0.2025   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
565                 0.05533  ...         23.69          38.25   
33                  0.06261  ...         24.15          30.90   
22                  0.07032  ...         18.07          19.08   
124                 0.05823  ...         14.26          22.75   
418                 0.06275  ...         13.65          16.92   
..                      ...  ...           ...            ...   
342                 0.06907  ...         11.92          19.90   
455                 0.06016  ...         15.05          41.61   
475                 0.05913  ...         14.09          19.35   
206                 0.06285  ...         10.42          23.22   
416                 0.06601  ...         10.85          31.24   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
565           155.00      1731.0            0.1166             0.1922   
33            161.40      1813.0            0.1509             0.6590   
22            125.10       980.9            0.1390             0.5954   
124            91.99       632.1            0.1025             0.2531   
418            88.12       566.9            0.1314             0.1607   
..               ...         ...               ...                ...   
342            79.76       440.0            0.1418             0.2210   
455            96.69       705.6            0.1172             0.1421   
475            93.22       605.8            0.1326             0.2610   
206            67.08       331.6            0.1415             0.1247   
416            68.73       359.4            0.1526             0.1193   

     concavity_worst  concave points_worst  symmetry_worst  \
565          0.32150               0.16280          0.2572   
33           0.60910               0.17850          0.3672   
22           0.63050               0.23930          0.4667   
124          0.33080               0.08978          0.2048   
418          0.09385               0.08224          0.2775   
..               ...                   ...             ...   
342          0.22990               0.10750         

In [7]:
y_train

565    M
33     M
22     M
124    B
418    B
      ..
342    B
455    B
475    B
206    B
416    B
Name: diagnosis, Length: 455, dtype: object

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [56]:
x_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [57]:
x_train_tensor.shape

torch.Size([455, 30])

In [58]:
y_train_tensor.shape

torch.Size([455])

In [67]:
class SimpleNN(nn.Module):
    def __init__(self,input_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_features,3),
            nn.ReLU(),
            nn.Linear(3,3),
            nn.ReLU(),
            nn.Linear(3,4),
            nn.ReLU(),
            nn.Linear(4,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        return self.network(features)
   

In [60]:
learning_rate = 0.1
epochs = 1000

In [ ]:
loss_function = nn.BCELoss() # Binary Cross Entropy Loss 

In [ ]:
model = SimpleNN(x_train_tensor.shape[1])
 ## defining optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)
for epoch in range(epochs):
    y_pred = model(x_train_tensor) ## forward pass 
    loss = loss_function(y_pred,y_train_tensor.view(-1,1)) ## compute loss
    optimizer.zero_grad() ## zero gradients
    loss.backward()
    optimizer.step() ## update parameters
    
    print(f'Epoch : {epoch+1} , loss : {loss.item()}')

Epoch : 1 , loss : 0.6911898851394653
Epoch : 2 , loss : 0.6890465617179871
Epoch : 3 , loss : 0.6870332956314087
Epoch : 4 , loss : 0.6851416230201721
Epoch : 5 , loss : 0.6833625435829163
Epoch : 6 , loss : 0.6816893815994263
Epoch : 7 , loss : 0.6801152229309082
Epoch : 8 , loss : 0.6786340475082397
Epoch : 9 , loss : 0.6772395968437195
Epoch : 10 , loss : 0.6759260296821594
Epoch : 11 , loss : 0.6746886968612671
Epoch : 12 , loss : 0.6735230088233948
Epoch : 13 , loss : 0.67242431640625
Epoch : 14 , loss : 0.6713884472846985
Epoch : 15 , loss : 0.6704114079475403
Epoch : 16 , loss : 0.6694900393486023
Epoch : 17 , loss : 0.6686207056045532
Epoch : 18 , loss : 0.66780024766922
Epoch : 19 , loss : 0.6670259833335876
Epoch : 20 , loss : 0.6662951111793518
Epoch : 21 , loss : 0.6656050086021423
Epoch : 22 , loss : 0.664953351020813
Epoch : 23 , loss : 0.6643377542495728
Epoch : 24 , loss : 0.6637561917304993
Epoch : 25 , loss : 0.6632066369056702
Epoch : 26 , loss : 0.6626874208450317


##### here model.parameters() is the iterator that will iterate over all the trainable parameters of the neural networks.

##### torch.optim is the optimizer class that contains various types of optimizers like SGD,Adam,RMSProp etc. , so instead of applying gradient decent and updation of parameters manually torch.optim is used to automate the backprop weight updation process

##### also we have the inbuilt loss functions in torch.nn module , which will reduce the effort of creating the loss function manually 

In [77]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Test Accuracy : {accuracy.item()*100} %')

Test Accuracy : 51.246535778045654 %


## Using Torch.nn for creating a neural network 

In [30]:
import torch
import torch.nn as nn 

In [31]:
class Model(nn.Module):
    def __init__(self,input_features):
        super().__init__()
        self.linear = nn.Linear(input_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        output = self.linear(features)
        output = self.sigmoid(output)
        return output 

In [32]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features) ## forward pass 

tensor([[0.4279],
        [0.5057],
        [0.4232],
        [0.5201],
        [0.4693],
        [0.5374],
        [0.4479],
        [0.4861],
        [0.4513],
        [0.3894]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight ## weights of linear layer

Parameter containing:
tensor([[-0.4140, -0.3101,  0.3940,  0.3329, -0.2601]], requires_grad=True)

In [34]:
model.linear.bias ## bias of linear layer

Parameter containing:
tensor([-0.0598], requires_grad=True)

In [35]:
!pip install torchinfo

In [36]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Creating NN with 2 hidden layers 

In [37]:
class Model(nn.Module):
    def __init__(self,input_features):
        super().__init__()
        self.linear1 = nn.Linear(input_features,3)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(3,3)
        self.relu2 = nn.ReLU()
        self.output = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        x = self.linear1(features)
        x = self.relu1(x)
        x = self.linear2(x)
        x = self.relu2(x)
        x = self.output(x)
        x = self.sigmoid(x)
        return x

In [38]:
features = torch.rand(10,5)
model = Model(input_features = features.shape[1])
model(features) ## forward pass

tensor([[0.5359],
        [0.5359],
        [0.5359],
        [0.5368],
        [0.5359],
        [0.5372],
        [0.5390],
        [0.5359],
        [0.5434],
        [0.5370]], grad_fn=<SigmoidBackward0>)

In [39]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3660, -0.1713,  0.1848, -0.3772,  0.3870],
        [ 0.1989,  0.1735,  0.3409, -0.2454,  0.1299],
        [ 0.3156,  0.1360, -0.2222, -0.2141, -0.3089]], requires_grad=True)

In [40]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5714,  0.3959,  0.1753],
        [ 0.4405, -0.2500, -0.0285],
        [ 0.1696,  0.5660, -0.0090]], requires_grad=True)

In [41]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 3]                   12
├─ReLU: 1-4                              [10, 3]                   --
├─Linear: 1-5                            [10, 1]                   4
├─Sigmoid: 1-6                           [10, 1]                   --
Total params: 34
Trainable params: 34
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Using Sequential Container 

In [ ]:
class Model1(nn.Module):
    def __init__(self,input_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_features,3), ## first hidden layer
            nn.ReLU(),
            nn.Linear(3,3), ## second hidden layer
            nn.ReLU(),
            nn.Linear(3,4), ## third hidden layer
            nn.ReLU(),
            nn.Linear(4,1), ## output layer
            nn.Sigmoid()
        )
    def forward(self,features):
        x = self.network(features)
        return x

In [51]:
features = torch.rand(10,5)
model1 = Model1(input_features=5)
model1(features) ## forward pass

tensor([[0.4863],
        [0.4749],
        [0.4648],
        [0.4676],
        [0.4685],
        [0.4667],
        [0.4757],
        [0.4769],
        [0.4664],
        [0.4600]], grad_fn=<SigmoidBackward0>)

In [52]:
summary(model1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 3]                   12
│    └─ReLU: 2-4                         [10, 3]                   --
│    └─Linear: 2-5                       [10, 4]                   16
│    └─ReLU: 2-6                         [10, 4]                   --
│    └─Linear: 2-7                       [10, 1]                   5
│    └─Sigmoid: 2-8                      [10, 1]                   --
Total params: 51
Trainable params: 51
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00